SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO emedic.posts (id, author_id, category_id, title, seo_title, excerpt, body, image, slug, meta_description, meta_keywords, status, featured, created_at, updated_at) VALUES (1, 0, null, 'Lorem Ipsum Post', null, 'This is the excerpt for the Lorem Ipsum Post', '<p>This is the body of the lorem ipsum post</p>', 'posts/post1.jpg', 'lorem-ipsum-post', 'This is the meta description', 'keyword1, keyword2, keyword3', 'PUBLISHED', 0, '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.posts (id, author_id, category_id, title, seo_title, excerpt, body, image, slug, meta_description, meta_keywords, status, featured, created_at, updated_at) VALUES (2, 0, null, 'My Sample Post', null, 'This is the excerpt for the sample Post', '<p>This is the body for the sample post, which includes the body.</p>
                <h2>We can use all kinds of format!</h2>
                <p>And include a bunch of other stuff.</p>', 'posts/post2.jpg', 'my-sample-post', 'Meta Description for sample post', 'keyword1, keyword2, keyword3', 'PUBLISHED', 0, '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.posts (id, author_id, category_id, title, seo_title, excerpt, body, image, slug, meta_description, meta_keywords, status, featured, created_at, updated_at) VALUES (3, 0, null, 'Latest Post', null, 'This is the excerpt for the latest post', '<p>This is the body for the latest post</p>', 'posts/post3.jpg', 'latest-post', 'This is the meta description', 'keyword1, keyword2, keyword3', 'PUBLISHED', 0, '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.posts (id, author_id, category_id, title, seo_title, excerpt, body, image, slug, meta_description, meta_keywords, status, featured, created_at, updated_at) VALUES (4, 0, null, 'Yarr Post', null, 'Reef sails nipperkin bring a spring upon her cable coffer jury mast spike marooned Pieces of Eight poop deck pillage. Clipper driver coxswain galleon hempen halter come about pressgang gangplank boatswain swing the lead. Nipperkin yard skysail swab lanyard Blimey bilge water ho quarter Buccaneer.', '<p>Swab deadlights Buccaneer fire ship square-rigged dance the hempen jig weigh anchor cackle fruit grog furl. Crack Jennys tea cup chase guns pressgang hearties spirits hogshead Gold Road six pounders fathom measured fer yer chains. Main sheet provost come about trysail barkadeer crimp scuttle mizzenmast brig plunder.</p>
<p>Mizzen league keelhaul galleon tender cog chase Barbary Coast doubloon crack Jennys tea cup. Blow the man down lugsail fire ship pinnace cackle fruit line warp Admiral of the Black strike colors doubloon. Tackle Jack Ketch come about crimp rum draft scuppers run a shot across the bow haul wind maroon.</p>
<p>Interloper heave down list driver pressgang holystone scuppers tackle scallywag bilged on her anchor. Jack Tar interloper draught grapple mizzenmast hulk knave cable transom hogshead. Gaff pillage to go on account grog aft chase guns piracy yardarm knave clap of thunder.</p>', 'posts/post4.jpg', 'yarr-post', 'this be a meta descript', 'keyword1, keyword2, keyword3', 'PUBLISHED', 0, '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (1, 1, 'id', 'number', 'ID', 1, 0, 0, 0, 0, 0, null, 1);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (2, 1, 'name', 'text', 'Name', 1, 1, 1, 1, 1, 1, null, 2);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (3, 1, 'email', 'text', 'Email', 1, 1, 1, 1, 1, 1, null, 3);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (4, 1, 'password', 'password', 'Password', 1, 0, 0, 1, 1, 0, null, 4);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (5, 1, 'remember_token', 'text', 'Remember Token', 0, 0, 0, 0, 0, 0, null, 5);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (6, 1, 'created_at', 'timestamp', 'Created At', 0, 1, 1, 0, 0, 0, null, 6);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (7, 1, 'updated_at', 'timestamp', 'Updated At', 0, 0, 0, 0, 0, 0, null, 7);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (8, 1, 'avatar', 'image', 'Avatar', 0, 1, 1, 1, 1, 1, null, 8);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (9, 1, 'user_belongsto_role_relationship', 'relationship', 'Role', 0, 1, 1, 1, 1, 0, '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":0}', 10);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (10, 1, 'user_belongstomany_role_relationship', 'relationship', 'Roles', 0, 1, 1, 1, 1, 0, '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}', 11);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (11, 1, 'locale', 'text', 'Locale', 0, 1, 1, 1, 1, 0, null, 12);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (12, 1, 'settings', 'hidden', 'Settings', 0, 0, 0, 0, 0, 0, null, 12);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (13, 2, 'id', 'number', 'ID', 1, 0, 0, 0, 0, 0, null, 1);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (14, 2, 'name', 'text', 'Name', 1, 1, 1, 1, 1, 1, null, 2);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (15, 2, 'created_at', 'timestamp', 'Created At', 0, 0, 0, 0, 0, 0, null, 3);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (16, 2, 'updated_at', 'timestamp', 'Updated At', 0, 0, 0, 0, 0, 0, null, 4);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (17, 3, 'id', 'number', 'ID', 1, 0, 0, 0, 0, 0, null, 1);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (18, 3, 'name', 'text', 'Name', 1, 1, 1, 1, 1, 1, null, 2);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (19, 3, 'created_at', 'timestamp', 'Created At', 0, 0, 0, 0, 0, 0, null, 3);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (20, 3, 'updated_at', 'timestamp', 'Updated At', 0, 0, 0, 0, 0, 0, null, 4);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (21, 3, 'display_name', 'text', 'Display Name', 1, 1, 1, 1, 1, 1, null, 5);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (22, 1, 'role_id', 'text', 'Role', 1, 1, 1, 1, 1, 1, null, 9);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (23, 4, 'id', 'number', 'ID', 1, 0, 0, 0, 0, 0, null, 1);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (24, 4, 'parent_id', 'select_dropdown', 'Parent', 0, 0, 1, 1, 1, 1, '{"default":"","null":"","options":{"":"-- None --"},"relationship":{"key":"id","label":"name"}}', 2);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (25, 4, 'order', 'text', 'Order', 1, 1, 1, 1, 1, 1, '{"default":1}', 3);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (26, 4, 'name', 'text', 'Name', 1, 1, 1, 1, 1, 1, null, 4);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (27, 4, 'slug', 'text', 'Slug', 1, 1, 1, 1, 1, 1, '{"slugify":{"origin":"name"}}', 5);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (28, 4, 'created_at', 'timestamp', 'Created At', 0, 0, 1, 0, 0, 0, null, 6);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (29, 4, 'updated_at', 'timestamp', 'Updated At', 0, 0, 0, 0, 0, 0, null, 7);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (30, 5, 'id', 'number', 'ID', 1, 0, 0, 0, 0, 0, null, 1);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (31, 5, 'author_id', 'text', 'Author', 1, 0, 1, 1, 0, 1, null, 2);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (32, 5, 'category_id', 'text', 'Category', 1, 0, 1, 1, 1, 0, null, 3);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (33, 5, 'title', 'text', 'Title', 1, 1, 1, 1, 1, 1, null, 4);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (34, 5, 'excerpt', 'text_area', 'Excerpt', 1, 0, 1, 1, 1, 1, null, 5);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (35, 5, 'body', 'rich_text_box', 'Body', 1, 0, 1, 1, 1, 1, null, 6);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (36, 5, 'image', 'image', 'Post Image', 0, 1, 1, 1, 1, 1, '{"resize":{"width":"1000","height":"null"},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":"250"}}]}', 7);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (37, 5, 'slug', 'text', 'Slug', 1, 0, 1, 1, 1, 1, '{"slugify":{"origin":"title","forceUpdate":true},"validation":{"rule":"unique:posts,slug"}}', 8);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (38, 5, 'meta_description', 'text_area', 'Meta Description', 1, 0, 1, 1, 1, 1, null, 9);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (39, 5, 'meta_keywords', 'text_area', 'Meta Keywords', 1, 0, 1, 1, 1, 1, null, 10);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (40, 5, 'status', 'select_dropdown', 'Status', 1, 1, 1, 1, 1, 1, '{"default":"DRAFT","options":{"PUBLISHED":"published","DRAFT":"draft","PENDING":"pending"}}', 11);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (41, 5, 'created_at', 'timestamp', 'Created At', 0, 1, 1, 0, 0, 0, null, 12);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (42, 5, 'updated_at', 'timestamp', 'Updated At', 0, 0, 0, 0, 0, 0, null, 13);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (43, 5, 'seo_title', 'text', 'SEO Title', 0, 1, 1, 1, 1, 1, null, 14);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (44, 5, 'featured', 'checkbox', 'Featured', 1, 1, 1, 1, 1, 1, null, 15);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (45, 6, 'id', 'number', 'ID', 1, 0, 0, 0, 0, 0, null, 1);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (46, 6, 'author_id', 'text', 'Author', 1, 0, 0, 0, 0, 0, null, 2);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (47, 6, 'title', 'text', 'Title', 1, 1, 1, 1, 1, 1, null, 3);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (48, 6, 'excerpt', 'text_area', 'Excerpt', 1, 0, 1, 1, 1, 1, null, 4);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (49, 6, 'body', 'rich_text_box', 'Body', 1, 0, 1, 1, 1, 1, null, 5);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (50, 6, 'slug', 'text', 'Slug', 1, 0, 1, 1, 1, 1, '{"slugify":{"origin":"title"},"validation":{"rule":"unique:pages,slug"}}', 6);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (51, 6, 'meta_description', 'text', 'Meta Description', 1, 0, 1, 1, 1, 1, null, 7);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (52, 6, 'meta_keywords', 'text', 'Meta Keywords', 1, 0, 1, 1, 1, 1, null, 8);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (53, 6, 'status', 'select_dropdown', 'Status', 1, 1, 1, 1, 1, 1, '{"default":"INACTIVE","options":{"INACTIVE":"INACTIVE","ACTIVE":"ACTIVE"}}', 9);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (54, 6, 'created_at', 'timestamp', 'Created At', 1, 1, 1, 0, 0, 0, null, 10);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (55, 6, 'updated_at', 'timestamp', 'Updated At', 1, 0, 0, 0, 0, 0, null, 11);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (56, 6, 'image', 'image', 'Page Image', 0, 1, 1, 1, 1, 1, null, 12);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (57, 7, 'id', 'text', 'Id', 1, 0, 0, 0, 0, 0, '{}', 1);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (58, 7, 'tipo', 'select_dropdown', 'Tipo', 1, 1, 1, 1, 1, 1, '{"default":"option1","options":{"option1":"Ingreso","option2":"Salida"}}', 4);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (59, 7, 'created_at', 'timestamp', 'Ingreso', 0, 1, 1, 0, 0, 0, '{"format":"%T"}', 6);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (60, 7, 'updated_at', 'timestamp', 'Salida', 0, 1, 1, 0, 0, 0, '{"format":"%T"}', 7);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (61, 8, 'id', 'text', 'Id', 1, 0, 0, 0, 0, 0, '{}', 1);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (62, 8, 'user_id', 'select_dropdown', 'Usuario', 1, 1, 1, 1, 1, 1, '{}', 2);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (63, 8, 'name', 'text', 'Nombre Completo', 1, 1, 1, 1, 1, 1, '{}', 6);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (64, 8, 'city', 'text', 'Ciudad', 0, 1, 1, 1, 1, 1, '{}', 7);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (65, 8, 'phone', 'text', 'Celular', 0, 1, 1, 1, 1, 1, '{}', 8);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (66, 8, 'created_at', 'timestamp', 'Fecha de Alta', 0, 1, 1, 0, 0, 0, '{}', 9);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (67, 8, 'updated_at', 'timestamp', 'Updated At', 0, 0, 0, 0, 0, 0, '{}', 10);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (68, 8, 'medico_belongsto_user_relationship', 'relationship', 'Usuario', 0, 1, 1, 1, 1, 1, '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"user_id","key":"id","label":"name","pivot_table":"asistencias","pivot":"0","taggable":"0"}', 3);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (69, 7, 'medico_id', 'select_dropdown', 'Medico', 1, 1, 1, 1, 1, 1, '{}', 2);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (70, 7, 'asistencia_belongsto_medico_relationship', 'relationship', 'Medico', 0, 1, 1, 1, 1, 1, '{"model":"App\\\\Medico","table":"medicos","type":"belongsTo","column":"medico_id","key":"id","label":"name","pivot_table":"asistencias","pivot":"0","taggable":"0"}', 3);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (71, 9, 'id', 'text', 'Id', 1, 0, 0, 0, 0, 0, '{}', 1);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (72, 9, 'name', 'text', 'Nombre', 1, 1, 1, 1, 1, 1, '{}', 2);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (73, 9, 'created_at', 'timestamp', 'Fecha de Alta', 0, 1, 1, 0, 0, 0, '{}', 3);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (74, 9, 'updated_at', 'timestamp', 'Updated At', 0, 0, 0, 0, 0, 0, '{}', 4);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (75, 10, 'id', 'text', 'Id', 1, 0, 0, 0, 0, 0, '{}', 1);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (76, 10, 'nombre', 'text', 'Nombre', 1, 1, 1, 1, 1, 1, '{}', 2);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (77, 10, 'empresa_id', 'select_dropdown', 'Empresa', 1, 1, 1, 1, 1, 1, '{}', 3);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (78, 10, 'created_at', 'timestamp', 'Fecha de Alta', 0, 1, 1, 0, 0, 0, '{}', 4);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (79, 10, 'updated_at', 'timestamp', 'Updated At', 0, 0, 0, 0, 0, 0, '{}', 5);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (80, 10, 'sede_belongsto_empresa_relationship', 'relationship', 'Empresa', 0, 1, 1, 1, 1, 1, '{"model":"App\\\\Empresa","table":"empresas","type":"belongsTo","column":"empresa_id","key":"id","label":"name","pivot_table":"asistencias","pivot":"0","taggable":"0"}', 6);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (81, 11, 'id', 'text', 'Id', 1, 0, 0, 0, 0, 0, '{}', 1);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (82, 11, 'codigo', 'text', 'Codigo', 1, 1, 1, 1, 1, 1, '{}', 2);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (83, 11, 'name', 'text', 'Name', 1, 1, 1, 1, 1, 1, '{}', 3);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (84, 11, 'created_at', 'timestamp', 'Creado', 0, 1, 1, 0, 0, 0, '{}', 4);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (85, 11, 'updated_at', 'timestamp', 'Updated At', 0, 0, 0, 0, 0, 0, '{}', 5);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (86, 12, 'id', 'text', 'Id', 1, 0, 0, 0, 0, 0, '{}', 1);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (87, 12, 'name', 'text', 'Name', 1, 1, 1, 1, 1, 1, '{}', 2);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (88, 12, 'created_at', 'timestamp', 'Creado', 0, 1, 1, 0, 0, 0, '{}', 3);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (89, 12, 'updated_at', 'timestamp', 'Updated At', 0, 0, 0, 0, 0, 0, '{}', 4);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (90, 13, 'id', 'text', 'Id', 1, 0, 0, 0, 0, 0, '{}', 1);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (91, 13, 'paciente_id', 'select_dropdown', 'Paciente', 1, 1, 1, 1, 1, 1, '{}', 2);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (92, 13, 'edad', 'text', 'Edad', 1, 1, 1, 1, 1, 1, '{}', 4);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (93, 13, 'genero', 'select_dropdown', 'Genero', 1, 1, 1, 1, 1, 1, '{"default":"option1","options":{"option1":"Masculino","option2":"Femenino"}}', 5);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (94, 13, 'area', 'text', 'Área', 0, 1, 1, 1, 1, 1, '{}', 6);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (95, 13, 'sintoma', 'text_area', 'Sintoma', 0, 1, 1, 1, 1, 1, '{}', 7);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (96, 13, 'diagnostico_id', 'select_dropdown', 'Diagnóstico', 1, 1, 1, 1, 1, 1, '{}', 8);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (97, 13, 'patologia_id', 'select_dropdown', 'Patología', 1, 1, 1, 1, 1, 1, '{}', 10);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (98, 13, 'imagen', 'multiple_images', 'Imagen', 0, 1, 1, 1, 1, 1, '{}', 11);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (99, 13, 'created_at', 'timestamp', 'Alta', 0, 1, 1, 0, 0, 0, '{}', 12);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (100, 13, 'updated_at', 'timestamp', 'Updated At', 0, 0, 0, 0, 0, 0, '{}', 13);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (101, 14, 'id', 'text', 'Id', 1, 0, 0, 0, 0, 0, '{}', 1);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (102, 14, 'nombre', 'text', 'Nombre', 1, 1, 1, 1, 1, 1, '{}', 2);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (103, 14, 'sede_id', 'select_dropdown', 'Sede', 1, 1, 1, 1, 1, 1, '{}', 3);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (104, 14, 'empresa_id', 'select_dropdown', 'Empresa', 1, 1, 1, 1, 1, 1, '{}', 5);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (105, 14, 'created_at', 'timestamp', 'Fecha de Alta', 0, 1, 1, 0, 0, 0, '{}', 7);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (106, 14, 'updated_at', 'timestamp', 'Updated At', 0, 0, 0, 0, 0, 0, '{}', 8);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (107, 14, 'paciente_belongsto_sede_relationship', 'relationship', 'Sede', 0, 1, 1, 1, 1, 1, '{"model":"App\\\\Sede","table":"sedes","type":"belongsTo","column":"sede_id","key":"id","label":"nombre","pivot_table":"asistencias","pivot":"0","taggable":"0"}', 4);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (108, 14, 'paciente_belongsto_empresa_relationship', 'relationship', 'Empresa', 0, 1, 1, 1, 1, 1, '{"model":"App\\\\Empresa","table":"empresas","type":"belongsTo","column":"empresa_id","key":"id","label":"name","pivot_table":"asistencias","pivot":"0","taggable":"0"}', 6);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (109, 13, 'formato_belongsto_paciente_relationship', 'relationship', 'Paciente', 0, 1, 1, 1, 1, 1, '{"model":"App\\\\Paciente","table":"pacientes","type":"belongsTo","column":"paciente_id","key":"id","label":"nombre","pivot_table":"asistencias","pivot":"0","taggable":"0"}', 3);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (110, 13, 'formato_belongsto_diagnostico_relationship', 'relationship', 'Diagnóstico', 0, 1, 1, 1, 1, 1, '{"model":"App\\\\Diagnostico","table":"diagnosticos","type":"belongsTo","column":"diagnostico_id","key":"id","label":"name","pivot_table":"asistencias","pivot":"0","taggable":"0"}', 9);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (111, 7, 'fecha', 'timestamp', 'Fecha', 0, 1, 1, 0, 0, 0, '{"format":"%d-%m-%Y"}', 5);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (112, 15, 'id', 'text', 'Id', 1, 0, 0, 0, 0, 0, '{}', 1);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (113, 15, 'medico_id', 'text', 'Medico Id', 1, 1, 1, 1, 1, 1, '{}', 2);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (114, 15, 'sede_id', 'text', 'Sede Id', 1, 1, 1, 1, 1, 1, '{}', 3);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (115, 15, 'mes', 'text', 'Mes', 0, 1, 1, 1, 1, 1, '{}', 4);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (116, 15, 'semana', 'text', 'Semana', 0, 1, 1, 1, 1, 1, '{}', 5);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (117, 15, 'dia', 'text', 'Dia', 0, 1, 1, 1, 1, 1, '{}', 6);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (118, 15, 'desde', 'text', 'Desde', 0, 1, 1, 1, 1, 1, '{}', 7);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (119, 15, 'hasta', 'text', 'Hasta', 0, 1, 1, 1, 1, 1, '{}', 8);
INSERT INTO emedic.data_rows (id, data_type_id, field, type, display_name, required, browse, `read`, edit, `add`, `delete`, details, `order`) VALUES (120, 7, 'ubicacion', 'text', 'Ubicación', 0, 1, 1, 0, 0, 0, '{}', 8);
INSERT INTO emedic.medicos (id, user_id, name, city, phone, created_at, updated_at) VALUES (1, 4, 'Layza Corrales Torres', 'Lima', '987806223', '2019-01-21 23:55:45', '2019-01-21 23:55:45');
INSERT INTO emedic.settings (id, `key`, display_name, value, details, type, `order`, `group`) VALUES (1, 'site.title', 'Site Title', 'MEDISEGUR', '', 'text', 1, 'Site');
INSERT INTO emedic.settings (id, `key`, display_name, value, details, type, `order`, `group`) VALUES (2, 'site.description', 'Site Description', 'Site Description', '', 'text', 2, 'Site');
INSERT INTO emedic.settings (id, `key`, display_name, value, details, type, `order`, `group`) VALUES (4, 'site.google_analytics_tracking_id', 'Google Analytics Tracking ID', null, '', 'text', 4, 'Site');
INSERT INTO emedic.settings (id, `key`, display_name, value, details, type, `order`, `group`) VALUES (5, 'admin.bg_image', 'Admin Background Image', 'settings\\December2018\\M7PshvlLHsOOHhvo2kwk.jpg', '', 'image', 5, 'Admin');
INSERT INTO emedic.settings (id, `key`, display_name, value, details, type, `order`, `group`) VALUES (6, 'admin.title', 'Admin Title', 'MEDISEGUR', '', 'text', 2, 'Admin');
INSERT INTO emedic.settings (id, `key`, display_name, value, details, type, `order`, `group`) VALUES (7, 'admin.description', 'Admin Description', 'Bienvenido a nuestro sistema de vigilancia médica.', '', 'text', 1, 'Admin');
INSERT INTO emedic.settings (id, `key`, display_name, value, details, type, `order`, `group`) VALUES (8, 'admin.loader', 'Admin Loader', '', '', 'image', 3, 'Admin');
INSERT INTO emedic.settings (id, `key`, display_name, value, details, type, `order`, `group`) VALUES (10, 'admin.google_analytics_client_id', 'Google Analytics Client ID (used for admin dashboard)', null, '', 'text', 1, 'Admin');
INSERT INTO emedic.settings (id, `key`, display_name, value, details, type, `order`, `group`) VALUES (12, 'admin.setting(''admin.logo'')', 'Admin Logo', 'settings\\January2019\\NoytxoqGOXVKm7GtAjf2.jpg', null, 'image', 6, 'Admin');
INSERT INTO emedic.settings (id, `key`, display_name, value, details, type, `order`, `group`) VALUES (13, 'site.logo', 'Site Logo', '', '', 'image', 3, 'Site');
INSERT INTO emedic.settings (id, `key`, display_name, value, details, type, `order`, `group`) VALUES (14, 'admin.icon_image', 'Admin Icon Image', '', '', 'image', 4, 'Admin');
INSERT INTO emedic.sedes (id, nombre, empresa_id, created_at, updated_at) VALUES (1, 'Tottus - San Miguel', 1, '2019-01-11 15:42:55', '2019-01-11 15:42:55');
INSERT INTO emedic.sedes (id, nombre, empresa_id, created_at, updated_at) VALUES (2, 'Tottus - Surco', 1, '2019-01-11 15:43:15', '2019-01-11 15:43:15');
INSERT INTO emedic.sedes (id, nombre, empresa_id, created_at, updated_at) VALUES (3, 'Metro - Chorrillos', 2, '2019-01-11 15:43:36', '2019-01-11 15:43:36');
INSERT INTO emedic.sedes (id, nombre, empresa_id, created_at, updated_at) VALUES (4, 'Lima', 4, '2019-01-11 17:40:14', '2019-01-11 17:40:14');
INSERT INTO emedic.asistencias (id, tipo, created_at, updated_at, medico_id, fecha, ubicacion) VALUES (4, 'option2', '2019-01-21 23:59:45', '2019-01-22 00:01:39', 1, null, null);
INSERT INTO emedic.categories (id, parent_id, `order`, name, slug, created_at, updated_at) VALUES (1, null, 1, 'Category 1', 'category-1', '2018-12-22 03:54:10', '2018-12-22 03:54:10');
INSERT INTO emedic.categories (id, parent_id, `order`, name, slug, created_at, updated_at) VALUES (2, null, 1, 'Category 2', 'category-2', '2018-12-22 03:54:10', '2018-12-22 03:54:10');
INSERT INTO emedic.pages (id, author_id, title, excerpt, body, image, slug, meta_description, meta_keywords, status, created_at, updated_at) VALUES (1, 0, 'Hello World', 'Hang the jib grog grog blossom grapple dance the hempen jig gangway pressgang bilge rat to go on account lugger. Nelsons folly gabion line draught scallywag fire ship gaff fluke fathom case shot. Sea Legs bilge rat sloop matey gabion long clothes run a shot across the bow Gold Road cog league.', '<p>Hello World. Scallywag grog swab Cat o''nine tails scuttle rigging hardtack cable nipper Yellow Jack. Handsomely spirits knave lad killick landlubber or just lubber deadlights chantey pinnace crack Jennys tea cup. Provost long clothes black spot Yellow Jack bilged on her anchor league lateen sail case shot lee tackle.</p>
<p>Ballast spirits fluke topmast me quarterdeck schooner landlubber or just lubber gabion belaying pin. Pinnace stern galleon starboard warp carouser to go on account dance the hempen jig jolly boat measured fer yer chains. Man-of-war fire in the hole nipperkin handsomely doubloon barkadeer Brethren of the Coast gibbet driver squiffy.</p>', 'pages/page1.jpg', 'hello-world', 'Yar Meta Description', 'Keyword1, Keyword2', 'ACTIVE', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.empresas (id, name, created_at, updated_at) VALUES (1, 'TOTTUS', '2019-01-11 15:42:05', '2019-01-11 15:42:05');
INSERT INTO emedic.empresas (id, name, created_at, updated_at) VALUES (2, 'METRO', '2019-01-11 15:42:13', '2019-01-11 15:42:13');
INSERT INTO emedic.empresas (id, name, created_at, updated_at) VALUES (3, 'VOLVERD6', '2019-01-11 15:44:34', '2019-01-11 15:44:34');
INSERT INTO emedic.empresas (id, name, created_at, updated_at) VALUES (4, 'RIPLEY', '2019-01-11 17:39:39', '2019-01-11 17:39:39');
INSERT INTO emedic.patologias (id, name, created_at, updated_at) VALUES (1, 'Respiratoria', '2019-01-11 15:48:34', '2019-01-11 15:48:34');
INSERT INTO emedic.patologias (id, name, created_at, updated_at) VALUES (2, 'Gastro Intestinal', '2019-01-11 15:48:47', '2019-01-11 15:48:47');
INSERT INTO emedic.patologias (id, name, created_at, updated_at) VALUES (3, 'Músculo-Esquelética', '2019-01-11 15:49:14', '2019-01-11 15:50:10');
INSERT INTO emedic.patologias (id, name, created_at, updated_at) VALUES (4, 'Urológica', '2019-01-11 15:49:51', '2019-01-11 15:49:51');
INSERT INTO emedic.patologias (id, name, created_at, updated_at) VALUES (5, 'Ginecológica', '2019-01-11 15:50:25', '2019-01-11 15:50:25');
INSERT INTO emedic.patologias (id, name, created_at, updated_at) VALUES (6, 'Dérmica', '2019-01-11 15:50:34', '2019-01-11 15:50:34');
INSERT INTO emedic.patologias (id, name, created_at, updated_at) VALUES (7, 'Cardiaca', '2019-01-11 15:50:45', '2019-01-11 15:50:45');
INSERT INTO emedic.patologias (id, name, created_at, updated_at) VALUES (8, 'Neurológica', '2019-01-11 15:51:11', '2019-01-11 15:51:11');
INSERT INTO emedic.patologias (id, name, created_at, updated_at) VALUES (9, 'Otorrinolaringológica', '2019-01-11 15:51:42', '2019-01-11 15:51:42');
INSERT INTO emedic.patologias (id, name, created_at, updated_at) VALUES (10, 'Endocrinológica', '2019-01-11 15:51:56', '2019-01-11 15:51:56');
INSERT INTO emedic.patologias (id, name, created_at, updated_at) VALUES (11, 'Urgencia Médica', '2019-01-11 15:52:12', '2019-01-11 15:52:12');
INSERT INTO emedic.patologias (id, name, created_at, updated_at) VALUES (12, 'Otras', '2019-01-11 15:52:38', '2019-01-11 15:52:38');
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (1, 1, 'Dashboard', '', '_self', 'voyager-boat', null, null, 1, '2018-12-22 03:54:08', '2018-12-22 03:54:08', 'voyager.dashboard', null);
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (2, 1, 'Media', '', '_self', 'voyager-images', null, 18, 4, '2018-12-22 03:54:08', '2019-01-11 12:06:16', 'voyager.media.index', null);
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (3, 1, 'Usuarios', '', '_self', 'voyager-person', '#000000', null, 3, '2018-12-22 03:54:08', '2019-01-11 11:29:45', 'voyager.users.index', 'null');
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (4, 1, 'Roles', '', '_self', 'voyager-lock', null, null, 2, '2018-12-22 03:54:08', '2018-12-22 03:54:08', 'voyager.roles.index', null);
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (5, 1, 'Herramientas', '', '_self', 'voyager-tools', '#000000', null, 4, '2018-12-22 03:54:08', '2019-01-11 11:30:24', null, '');
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (6, 1, 'Menu Builder', '', '_self', 'voyager-list', null, 5, 1, '2018-12-22 03:54:08', '2018-12-25 10:56:04', 'voyager.menus.index', null);
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (7, 1, 'Database', '', '_self', 'voyager-data', null, 5, 2, '2018-12-22 03:54:08', '2018-12-25 10:56:04', 'voyager.database.index', null);
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (8, 1, 'Compass', '', '_self', 'voyager-compass', null, 5, 3, '2018-12-22 03:54:08', '2018-12-25 10:56:04', 'voyager.compass.index', null);
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (9, 1, 'BREAD', '', '_self', 'voyager-bread', null, 5, 4, '2018-12-22 03:54:08', '2018-12-25 10:56:04', 'voyager.bread.index', null);
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (10, 1, 'Configuración', '', '_self', 'voyager-settings', '#000000', null, 5, '2018-12-22 03:54:08', '2019-01-11 11:30:59', 'voyager.settings.index', 'null');
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (14, 1, 'Hooks', '', '_self', 'voyager-hook', null, 5, 5, '2018-12-22 03:54:11', '2018-12-25 10:56:04', 'voyager.hooks', null);
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (15, 1, 'Pages', '', '_self', 'voyager-documentation', '#000000', 18, 1, '2018-12-25 10:55:43', '2019-01-11 12:05:48', 'voyager.pages.index', 'null');
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (16, 1, 'Categories', '', '_self', 'voyager-categories', null, 18, 3, '2019-01-06 12:26:23', '2019-01-11 12:05:48', 'voyager.categories.index', null);
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (17, 1, 'Posts', '', '_self', 'voyager-news', null, 18, 2, '2019-01-06 12:26:23', '2019-01-11 12:05:48', 'voyager.posts.index', null);
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (18, 1, 'Documentos', '', '_self', 'voyager-documentation', '#000000', null, 6, '2019-01-11 12:05:31', '2019-01-11 12:06:16', null, '');
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (19, 1, 'Asistencias', '', '_self', 'voyager-check-circle', '#000000', 30, 2, '2019-01-11 12:11:44', '2019-01-11 11:48:10', 'voyager.asistencias.index', 'null');
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (20, 1, 'Medicos', '', '_self', 'voyager-group', null, 28, 1, '2019-01-11 12:17:02', '2019-01-11 11:35:37', 'voyager.medicos.index', null);
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (21, 1, 'Empresas', '', '_self', 'voyager-company', '#000000', 27, 1, '2019-01-11 12:24:47', '2019-01-11 11:33:31', 'voyager.empresas.index', 'null');
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (22, 1, 'Sedes', '', '_self', 'voyager-shop', null, 27, 2, '2019-01-11 12:27:22', '2019-01-11 11:33:34', 'voyager.sedes.index', null);
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (23, 1, 'Diagnosticos', '', '_self', 'voyager-edit', null, 29, 1, '2019-01-11 14:40:19', '2019-01-11 11:38:41', 'voyager.diagnosticos.index', null);
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (24, 1, 'Patologias', '', '_self', 'voyager-rum-1', null, 29, 3, '2019-01-11 14:44:57', '2019-01-11 11:38:41', 'voyager.patologias.index', null);
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (25, 1, 'Formatos', '', '_self', 'voyager-news', null, 29, 2, '2019-01-11 14:58:09', '2019-01-11 11:38:41', 'voyager.formatos.index', null);
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (26, 1, 'Pacientes', '', '_self', 'voyager-people', null, 28, 2, '2019-01-11 15:04:09', '2019-01-11 11:35:37', 'voyager.pacientes.index', null);
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (27, 1, 'Compañía', '', '_self', 'voyager-company', '#000000', null, 9, '2019-01-11 11:31:41', '2019-01-11 11:39:32', null, '');
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (28, 1, 'Personas', '', '_self', 'voyager-group', '#000000', null, 10, '2019-01-11 11:35:21', '2019-01-11 11:39:32', null, '');
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (29, 1, 'Vigilancia', '', '_self', 'voyager-edit', '#000000', null, 8, '2019-01-11 11:38:14', '2019-01-11 11:39:32', null, '');
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (30, 1, 'Horario', '', '_self', 'voyager-calendar', '#000000', null, 7, '2019-01-11 11:39:17', '2019-01-11 11:39:31', null, '');
INSERT INTO emedic.menu_items (id, menu_id, title, url, target, icon_class, color, parent_id, `order`, created_at, updated_at, route, parameters) VALUES (31, 1, 'Calendarios', '', '_self', 'voyager-calendar', null, 30, 1, '2019-01-11 11:47:54', '2019-01-11 11:48:10', 'voyager.calendarios.index', null);
INSERT INTO emedic.menus (id, name, created_at, updated_at) VALUES (1, 'admin', '2018-12-22 03:54:08', '2018-12-22 03:54:08');
INSERT INTO emedic.pacientes (id, nombre, sede_id, empresa_id, created_at, updated_at) VALUES (1, 'Max Manuel Camiña Azaña', null, 3, '2019-01-11 15:46:48', '2019-01-11 15:46:48');
INSERT INTO emedic.pacientes (id, nombre, sede_id, empresa_id, created_at, updated_at) VALUES (2, 'Luis Castro', 1, 1, '2019-01-11 15:47:26', '2019-01-11 15:47:26');
INSERT INTO emedic.diagnosticos (id, codigo, name, created_at, updated_at) VALUES (1, 'A103', 'Tos crónica', '2019-01-11 15:53:20', '2019-01-11 15:53:20');
INSERT INTO emedic.diagnosticos (id, codigo, name, created_at, updated_at) VALUES (2, 'N203', 'Dermatitis', '2019-01-11 15:53:57', '2019-01-11 15:53:57');
INSERT INTO emedic.roles (id, name, display_name, created_at, updated_at) VALUES (1, 'admin', 'Administrator', '2018-12-22 03:54:08', '2018-12-25 10:54:18');
INSERT INTO emedic.roles (id, name, display_name, created_at, updated_at) VALUES (2, 'medico', 'Médico', '2019-01-03 11:43:02', '2019-01-03 11:43:43');
INSERT INTO emedic.roles (id, name, display_name, created_at, updated_at) VALUES (3, 'user', 'Normal User', '2019-01-06 12:26:23', '2019-01-06 12:26:23');
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (1, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (1, 2);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (2, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (3, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (4, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (4, 2);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (5, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (6, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (6, 2);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (7, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (7, 2);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (8, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (9, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (10, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (11, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (11, 2);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (12, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (12, 2);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (13, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (14, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (15, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (16, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (16, 2);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (17, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (17, 2);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (18, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (18, 2);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (19, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (19, 2);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (20, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (21, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (22, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (23, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (24, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (25, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (26, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (27, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (28, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (29, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (30, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (31, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (32, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (33, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (34, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (35, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (36, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (37, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (38, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (39, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (40, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (41, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (42, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (42, 2);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (43, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (43, 2);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (44, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (44, 2);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (45, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (45, 2);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (46, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (47, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (48, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (49, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (50, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (51, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (52, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (53, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (54, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (55, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (56, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (57, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (58, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (59, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (60, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (61, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (62, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (63, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (64, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (65, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (66, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (67, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (68, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (69, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (70, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (71, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (72, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (73, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (74, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (75, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (76, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (77, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (78, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (79, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (80, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (81, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (82, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (83, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (84, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (85, 1);
INSERT INTO emedic.permission_role (permission_id, role_id) VALUES (86, 1);
INSERT INTO emedic.data_types (id, name, slug, display_name_singular, display_name_plural, icon, model_name, policy_name, controller, description, generate_permissions, server_side, details, created_at, updated_at) VALUES (1, 'users', 'users', 'User', 'Users', 'voyager-person', 'TCG\\Voyager\\Models\\User', 'TCG\\Voyager\\Policies\\UserPolicy', '', '', 1, 0, null, '2018-12-22 03:54:08', '2018-12-22 03:54:08');
INSERT INTO emedic.data_types (id, name, slug, display_name_singular, display_name_plural, icon, model_name, policy_name, controller, description, generate_permissions, server_side, details, created_at, updated_at) VALUES (2, 'menus', 'menus', 'Menu', 'Menus', 'voyager-list', 'TCG\\Voyager\\Models\\Menu', null, '', '', 1, 0, null, '2018-12-22 03:54:08', '2018-12-22 03:54:08');
INSERT INTO emedic.data_types (id, name, slug, display_name_singular, display_name_plural, icon, model_name, policy_name, controller, description, generate_permissions, server_side, details, created_at, updated_at) VALUES (3, 'roles', 'roles', 'Role', 'Roles', 'voyager-lock', 'TCG\\Voyager\\Models\\Role', null, '', '', 1, 0, null, '2018-12-22 03:54:08', '2018-12-22 03:54:08');
INSERT INTO emedic.data_types (id, name, slug, display_name_singular, display_name_plural, icon, model_name, policy_name, controller, description, generate_permissions, server_side, details, created_at, updated_at) VALUES (4, 'categories', 'categories', 'Category', 'Categories', 'voyager-categories', 'TCG\\Voyager\\Models\\Category', null, '', '', 1, 0, null, '2018-12-22 03:54:10', '2018-12-22 03:54:10');
INSERT INTO emedic.data_types (id, name, slug, display_name_singular, display_name_plural, icon, model_name, policy_name, controller, description, generate_permissions, server_side, details, created_at, updated_at) VALUES (5, 'posts', 'posts', 'Post', 'Posts', 'voyager-news', 'TCG\\Voyager\\Models\\Post', 'TCG\\Voyager\\Policies\\PostPolicy', '', '', 1, 0, null, '2018-12-22 03:54:10', '2018-12-22 03:54:10');
INSERT INTO emedic.data_types (id, name, slug, display_name_singular, display_name_plural, icon, model_name, policy_name, controller, description, generate_permissions, server_side, details, created_at, updated_at) VALUES (6, 'pages', 'pages', 'Page', 'Pages', 'voyager-file-text', 'TCG\\Voyager\\Models\\Page', null, '', '', 1, 0, null, '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.data_types (id, name, slug, display_name_singular, display_name_plural, icon, model_name, policy_name, controller, description, generate_permissions, server_side, details, created_at, updated_at) VALUES (7, 'asistencias', 'asistencias', 'Asistencia', 'Asistencias', 'voyager-check', 'App\\Asistencia', null, null, null, 1, 0, '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}', '2019-01-11 12:11:44', '2019-01-22 00:01:25');
INSERT INTO emedic.data_types (id, name, slug, display_name_singular, display_name_plural, icon, model_name, policy_name, controller, description, generate_permissions, server_side, details, created_at, updated_at) VALUES (8, 'medicos', 'medicos', 'Medico', 'Medicos', 'voyager-group', 'App\\Medico', null, null, null, 1, 0, '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}', '2019-01-11 12:17:02', '2019-01-21 23:55:25');
INSERT INTO emedic.data_types (id, name, slug, display_name_singular, display_name_plural, icon, model_name, policy_name, controller, description, generate_permissions, server_side, details, created_at, updated_at) VALUES (9, 'empresas', 'empresas', 'Empresa', 'Empresas', null, 'App\\Empresa', null, null, null, 1, 0, '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}', '2019-01-11 12:24:47', '2019-01-11 12:24:47');
INSERT INTO emedic.data_types (id, name, slug, display_name_singular, display_name_plural, icon, model_name, policy_name, controller, description, generate_permissions, server_side, details, created_at, updated_at) VALUES (10, 'sedes', 'sedes', 'Sede', 'Sedes', 'voyager-shop', 'App\\Sede', null, null, null, 1, 0, '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}', '2019-01-11 12:27:22', '2019-01-11 12:30:11');
INSERT INTO emedic.data_types (id, name, slug, display_name_singular, display_name_plural, icon, model_name, policy_name, controller, description, generate_permissions, server_side, details, created_at, updated_at) VALUES (11, 'diagnosticos', 'diagnosticos', 'Diagnostico', 'Diagnosticos', 'voyager-edit', 'App\\Diagnostico', null, null, null, 1, 0, '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}', '2019-01-11 14:40:19', '2019-01-11 14:40:19');
INSERT INTO emedic.data_types (id, name, slug, display_name_singular, display_name_plural, icon, model_name, policy_name, controller, description, generate_permissions, server_side, details, created_at, updated_at) VALUES (12, 'patologias', 'patologias', 'Patologia', 'Patologias', 'voyager-rum-1', 'App\\Patologia', null, null, null, 1, 0, '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}', '2019-01-11 14:44:57', '2019-01-11 14:44:57');
INSERT INTO emedic.data_types (id, name, slug, display_name_singular, display_name_plural, icon, model_name, policy_name, controller, description, generate_permissions, server_side, details, created_at, updated_at) VALUES (13, 'formatos', 'formatos', 'Formato', 'Formatos', 'voyager-news', 'App\\Formato', null, null, null, 1, 0, '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}', '2019-01-11 14:58:09', '2019-01-11 15:36:40');
INSERT INTO emedic.data_types (id, name, slug, display_name_singular, display_name_plural, icon, model_name, policy_name, controller, description, generate_permissions, server_side, details, created_at, updated_at) VALUES (14, 'pacientes', 'pacientes', 'Paciente', 'Pacientes', 'voyager-people', 'App\\Paciente', null, null, null, 1, 0, '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}', '2019-01-11 15:04:09', '2019-01-11 15:07:33');
INSERT INTO emedic.data_types (id, name, slug, display_name_singular, display_name_plural, icon, model_name, policy_name, controller, description, generate_permissions, server_side, details, created_at, updated_at) VALUES (15, 'calendarios', 'calendarios', 'Calendario', 'Calendarios', 'voyager-calendar', 'App\\Calendario', null, null, null, 1, 0, '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}', '2019-01-11 11:47:54', '2019-01-11 11:47:54');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (1, 'data_types', 'display_name_singular', 5, 'pt', 'Post', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (2, 'data_types', 'display_name_singular', 6, 'pt', 'Página', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (3, 'data_types', 'display_name_singular', 1, 'pt', 'Utilizador', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (4, 'data_types', 'display_name_singular', 4, 'pt', 'Categoria', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (5, 'data_types', 'display_name_singular', 2, 'pt', 'Menu', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (6, 'data_types', 'display_name_singular', 3, 'pt', 'Função', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (7, 'data_types', 'display_name_plural', 5, 'pt', 'Posts', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (8, 'data_types', 'display_name_plural', 6, 'pt', 'Páginas', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (9, 'data_types', 'display_name_plural', 1, 'pt', 'Utilizadores', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (10, 'data_types', 'display_name_plural', 4, 'pt', 'Categorias', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (11, 'data_types', 'display_name_plural', 2, 'pt', 'Menus', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (12, 'data_types', 'display_name_plural', 3, 'pt', 'Funções', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (13, 'categories', 'slug', 1, 'pt', 'categoria-1', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (14, 'categories', 'name', 1, 'pt', 'Categoria 1', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (15, 'categories', 'slug', 2, 'pt', 'categoria-2', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (16, 'categories', 'name', 2, 'pt', 'Categoria 2', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (17, 'pages', 'title', 1, 'pt', 'Olá Mundo', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (18, 'pages', 'slug', 1, 'pt', 'ola-mundo', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (19, 'pages', 'body', 1, 'pt', '<p>Olá Mundo. Scallywag grog swab Cat o''nine tails scuttle rigging hardtack cable nipper Yellow Jack. Handsomely spirits knave lad killick landlubber or just lubber deadlights chantey pinnace crack Jennys tea cup. Provost long clothes black spot Yellow Jack bilged on her anchor league lateen sail case shot lee tackle.</p>
<p>Ballast spirits fluke topmast me quarterdeck schooner landlubber or just lubber gabion belaying pin. Pinnace stern galleon starboard warp carouser to go on account dance the hempen jig jolly boat measured fer yer chains. Man-of-war fire in the hole nipperkin handsomely doubloon barkadeer Brethren of the Coast gibbet driver squiffy.</p>', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (20, 'menu_items', 'title', 1, 'pt', 'Painel de Controle', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (21, 'menu_items', 'title', 2, 'pt', 'Media', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (22, 'menu_items', 'title', 12, 'pt', 'Publicações', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (23, 'menu_items', 'title', 3, 'pt', 'Utilizadores', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (24, 'menu_items', 'title', 11, 'pt', 'Categorias', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (25, 'menu_items', 'title', 13, 'pt', 'Páginas', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (26, 'menu_items', 'title', 4, 'pt', 'Funções', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (27, 'menu_items', 'title', 5, 'pt', 'Ferramentas', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (28, 'menu_items', 'title', 6, 'pt', 'Menus', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (29, 'menu_items', 'title', 7, 'pt', 'Base de dados', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (30, 'menu_items', 'title', 10, 'pt', 'Configurações', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (31, 'menu_items', 'title', 17, 'pt', 'Publicações', '2019-01-06 12:26:24', '2019-01-06 12:26:24');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (32, 'menu_items', 'title', 16, 'pt', 'Categorias', '2019-01-06 12:26:24', '2019-01-06 12:26:24');
INSERT INTO emedic.translations (id, table_name, column_name, foreign_key, locale, value, created_at, updated_at) VALUES (33, 'menu_items', 'title', 15, 'pt', 'Páginas', '2019-01-06 12:26:24', '2019-01-06 12:26:24');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (1, 'browse_admin', null, '2018-12-22 03:54:08', '2018-12-22 03:54:08');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (2, 'browse_bread', null, '2018-12-22 03:54:08', '2018-12-22 03:54:08');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (3, 'browse_database', null, '2018-12-22 03:54:08', '2018-12-22 03:54:08');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (4, 'browse_media', null, '2018-12-22 03:54:08', '2018-12-22 03:54:08');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (5, 'browse_compass', null, '2018-12-22 03:54:08', '2018-12-22 03:54:08');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (6, 'browse_menus', 'menus', '2018-12-22 03:54:08', '2018-12-22 03:54:08');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (7, 'read_menus', 'menus', '2018-12-22 03:54:08', '2018-12-22 03:54:08');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (8, 'edit_menus', 'menus', '2018-12-22 03:54:08', '2018-12-22 03:54:08');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (9, 'add_menus', 'menus', '2018-12-22 03:54:08', '2018-12-22 03:54:08');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (10, 'delete_menus', 'menus', '2018-12-22 03:54:08', '2018-12-22 03:54:08');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (11, 'browse_roles', 'roles', '2018-12-22 03:54:08', '2018-12-22 03:54:08');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (12, 'read_roles', 'roles', '2018-12-22 03:54:08', '2018-12-22 03:54:08');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (13, 'edit_roles', 'roles', '2018-12-22 03:54:09', '2018-12-22 03:54:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (14, 'add_roles', 'roles', '2018-12-22 03:54:09', '2018-12-22 03:54:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (15, 'delete_roles', 'roles', '2018-12-22 03:54:09', '2018-12-22 03:54:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (16, 'browse_users', 'users', '2018-12-22 03:54:09', '2018-12-22 03:54:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (17, 'read_users', 'users', '2018-12-22 03:54:09', '2018-12-22 03:54:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (18, 'edit_users', 'users', '2018-12-22 03:54:09', '2018-12-22 03:54:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (19, 'add_users', 'users', '2018-12-22 03:54:09', '2018-12-22 03:54:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (20, 'delete_users', 'users', '2018-12-22 03:54:09', '2018-12-22 03:54:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (21, 'browse_settings', 'settings', '2018-12-22 03:54:09', '2018-12-22 03:54:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (22, 'read_settings', 'settings', '2018-12-22 03:54:09', '2018-12-22 03:54:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (23, 'edit_settings', 'settings', '2018-12-22 03:54:09', '2018-12-22 03:54:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (24, 'add_settings', 'settings', '2018-12-22 03:54:09', '2018-12-22 03:54:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (25, 'delete_settings', 'settings', '2018-12-22 03:54:09', '2018-12-22 03:54:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (26, 'browse_categories', 'categories', '2018-12-22 03:54:10', '2018-12-22 03:54:10');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (27, 'read_categories', 'categories', '2018-12-22 03:54:10', '2018-12-22 03:54:10');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (28, 'edit_categories', 'categories', '2018-12-22 03:54:10', '2018-12-22 03:54:10');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (29, 'add_categories', 'categories', '2018-12-22 03:54:10', '2018-12-22 03:54:10');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (30, 'delete_categories', 'categories', '2018-12-22 03:54:10', '2018-12-22 03:54:10');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (31, 'browse_posts', 'posts', '2018-12-22 03:54:10', '2018-12-22 03:54:10');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (32, 'read_posts', 'posts', '2018-12-22 03:54:10', '2018-12-22 03:54:10');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (33, 'edit_posts', 'posts', '2018-12-22 03:54:10', '2018-12-22 03:54:10');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (34, 'add_posts', 'posts', '2018-12-22 03:54:10', '2018-12-22 03:54:10');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (35, 'delete_posts', 'posts', '2018-12-22 03:54:10', '2018-12-22 03:54:10');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (36, 'browse_pages', 'pages', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (37, 'read_pages', 'pages', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (38, 'edit_pages', 'pages', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (39, 'add_pages', 'pages', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (40, 'delete_pages', 'pages', '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (41, 'browse_hooks', null, '2018-12-22 03:54:11', '2018-12-22 03:54:11');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (42, 'browse_asistencias', 'asistencias', '2019-01-11 12:11:44', '2019-01-11 12:11:44');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (43, 'read_asistencias', 'asistencias', '2019-01-11 12:11:44', '2019-01-11 12:11:44');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (44, 'edit_asistencias', 'asistencias', '2019-01-11 12:11:44', '2019-01-11 12:11:44');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (45, 'add_asistencias', 'asistencias', '2019-01-11 12:11:44', '2019-01-11 12:11:44');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (46, 'delete_asistencias', 'asistencias', '2019-01-11 12:11:44', '2019-01-11 12:11:44');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (47, 'browse_medicos', 'medicos', '2019-01-11 12:17:02', '2019-01-11 12:17:02');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (48, 'read_medicos', 'medicos', '2019-01-11 12:17:02', '2019-01-11 12:17:02');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (49, 'edit_medicos', 'medicos', '2019-01-11 12:17:02', '2019-01-11 12:17:02');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (50, 'add_medicos', 'medicos', '2019-01-11 12:17:02', '2019-01-11 12:17:02');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (51, 'delete_medicos', 'medicos', '2019-01-11 12:17:02', '2019-01-11 12:17:02');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (52, 'browse_empresas', 'empresas', '2019-01-11 12:24:47', '2019-01-11 12:24:47');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (53, 'read_empresas', 'empresas', '2019-01-11 12:24:47', '2019-01-11 12:24:47');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (54, 'edit_empresas', 'empresas', '2019-01-11 12:24:47', '2019-01-11 12:24:47');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (55, 'add_empresas', 'empresas', '2019-01-11 12:24:47', '2019-01-11 12:24:47');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (56, 'delete_empresas', 'empresas', '2019-01-11 12:24:47', '2019-01-11 12:24:47');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (57, 'browse_sedes', 'sedes', '2019-01-11 12:27:22', '2019-01-11 12:27:22');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (58, 'read_sedes', 'sedes', '2019-01-11 12:27:22', '2019-01-11 12:27:22');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (59, 'edit_sedes', 'sedes', '2019-01-11 12:27:22', '2019-01-11 12:27:22');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (60, 'add_sedes', 'sedes', '2019-01-11 12:27:22', '2019-01-11 12:27:22');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (61, 'delete_sedes', 'sedes', '2019-01-11 12:27:22', '2019-01-11 12:27:22');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (62, 'browse_diagnosticos', 'diagnosticos', '2019-01-11 14:40:19', '2019-01-11 14:40:19');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (63, 'read_diagnosticos', 'diagnosticos', '2019-01-11 14:40:19', '2019-01-11 14:40:19');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (64, 'edit_diagnosticos', 'diagnosticos', '2019-01-11 14:40:19', '2019-01-11 14:40:19');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (65, 'add_diagnosticos', 'diagnosticos', '2019-01-11 14:40:19', '2019-01-11 14:40:19');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (66, 'delete_diagnosticos', 'diagnosticos', '2019-01-11 14:40:19', '2019-01-11 14:40:19');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (67, 'browse_patologias', 'patologias', '2019-01-11 14:44:57', '2019-01-11 14:44:57');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (68, 'read_patologias', 'patologias', '2019-01-11 14:44:57', '2019-01-11 14:44:57');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (69, 'edit_patologias', 'patologias', '2019-01-11 14:44:57', '2019-01-11 14:44:57');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (70, 'add_patologias', 'patologias', '2019-01-11 14:44:57', '2019-01-11 14:44:57');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (71, 'delete_patologias', 'patologias', '2019-01-11 14:44:57', '2019-01-11 14:44:57');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (72, 'browse_formatos', 'formatos', '2019-01-11 14:58:09', '2019-01-11 14:58:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (73, 'read_formatos', 'formatos', '2019-01-11 14:58:09', '2019-01-11 14:58:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (74, 'edit_formatos', 'formatos', '2019-01-11 14:58:09', '2019-01-11 14:58:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (75, 'add_formatos', 'formatos', '2019-01-11 14:58:09', '2019-01-11 14:58:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (76, 'delete_formatos', 'formatos', '2019-01-11 14:58:09', '2019-01-11 14:58:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (77, 'browse_pacientes', 'pacientes', '2019-01-11 15:04:09', '2019-01-11 15:04:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (78, 'read_pacientes', 'pacientes', '2019-01-11 15:04:09', '2019-01-11 15:04:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (79, 'edit_pacientes', 'pacientes', '2019-01-11 15:04:09', '2019-01-11 15:04:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (80, 'add_pacientes', 'pacientes', '2019-01-11 15:04:09', '2019-01-11 15:04:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (81, 'delete_pacientes', 'pacientes', '2019-01-11 15:04:09', '2019-01-11 15:04:09');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (82, 'browse_calendarios', 'calendarios', '2019-01-11 11:47:54', '2019-01-11 11:47:54');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (83, 'read_calendarios', 'calendarios', '2019-01-11 11:47:54', '2019-01-11 11:47:54');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (84, 'edit_calendarios', 'calendarios', '2019-01-11 11:47:54', '2019-01-11 11:47:54');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (85, 'add_calendarios', 'calendarios', '2019-01-11 11:47:54', '2019-01-11 11:47:54');
INSERT INTO emedic.permissions (id, `key`, table_name, created_at, updated_at) VALUES (86, 'delete_calendarios', 'calendarios', '2019-01-11 11:47:54', '2019-01-11 11:47:54');
INSERT INTO emedic.users (id, role_id, name, email, avatar, email_verified_at, password, remember_token, settings, created_at, updated_at) VALUES (1, 1, 'admin', 'admin@admin.com', 'users\\January2019\\krgM6jg3EgsZjy2yqxaO.png', null, '$2y$10$wDVN/xxOc5PTMUW4ZYZqieTtglIMeG/M8ecvXmlD1lU7GCCupwjzO', 'e52H6yqmlTmNuEbXQmpumUutVLf3eHqad14pwrAmrcX1Yj7HB5XpT6YBthnZ', '{"locale":"en"}', '2018-12-22 03:54:10', '2019-01-03 11:39:21');
INSERT INTO emedic.users (id, role_id, name, email, avatar, email_verified_at, password, remember_token, settings, created_at, updated_at) VALUES (2, 2, 'medico1', 'medico1@medico.com', 'users\\January2019\\HI6ox5ZfiYR9fbonOGyy.png', null, '$2y$10$xCVeq3/742mS1jdkfkRwSOvU9lzdBdyKasnQ1praWUXYeKFTketBm', 'nA373ZNLiDXFsBaxhkaR8qxCV9d7X1CJcAWT7waaJSHJin12mXMOP7Jh9LfV', '{"locale":"es"}', '2019-01-03 11:41:44', '2019-01-11 11:23:52');
INSERT INTO emedic.users (id, role_id, name, email, avatar, email_verified_at, password, remember_token, settings, created_at, updated_at) VALUES (3, 2, 'medico2', 'medico2@medico.com', 'users\\January2019\\Io29KHcRx9vYKAUVfAuv.png', null, '$2y$10$UMZkA6hfS24TgSOy0fCzn.IRjsgdPXchYI0ddW7EobT.W/bOQzQ8y', null, '{"locale":"es"}', '2019-01-11 11:24:41', '2019-01-11 11:26:44');
INSERT INTO emedic.users (id, role_id, name, email, avatar, email_verified_at, password, remember_token, settings, created_at, updated_at) VALUES (4, 2, 'Dr. Layza', 'layza@medisegur.com', 'users/default.png', null, '$2y$10$2DbaY8U4SVBcU4hO7NyXmerUpubdeoOcUDDdhdqw/JMkiE3Wlcwri', '7iI8R2W0gaT8KQ5m0RmUjFTbEn7knhxsEX657iUuFH4GgSVAiXcR2YpmwPjQ', '{"locale":"es"}', '2019-01-11 17:43:03', '2019-01-21 23:49:22');



SET FOREIGN_KEY_CHECKS = 1;
